// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTU1XcGMvWXgraXVpM3dvUVNKdXAzdW5maWprb0QvQW8vOUptaktUSC9WZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZVFQSEgwbTBzK0cwUzlUNG9PcHR3Rm1TQUEzTW1yeUU4UENvZTduVkl6QT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBTWZMVEMvWnFUaXBCTW04ei9ZNHhhTEV0bE1aeEtCWEw3ZDJZNW5wdW04PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhdTJsRmhpcU9oOGN4LzEzZmc5b0JtejFPUWswSU1URDVxclg0bmZFbERFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InFDSEJHNDJoRkMzV1RldWV6Zjk1WVNFUlg5RzNYTlRoaVRRQy9rU1RZMjg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRYUHU0ZitjTWJxay9RNDRoWUx1VVNrQ0NXOEtlT0NiamR4UUpndWZBMHM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkZZRC80enNCWDd0MXJwUU8vdjhRa1FlR0R3VEJqT3JXRUtrT0JHRWZrST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTjJwRS9GVUxvWU1oMjJQMEtQL1lvcTZsdXJ3ZElUTFA0THY2anYyZkRpdz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlRMZzZNV3lPVTBDcnB5N3JSdmc1VjdEdktnSXVHaTZaTnFVSVBqY2toNnM2ZnBHcGpFblBCdXJ4bmcrU0lkby9zM3d2Um5iU1hkUWxOMGNreXowbUFnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODIsImFkdlNlY3JldEtleSI6ImJIdjE3eVN4d0hkSW4xOHVKMkJvVlpxL0ZHUjhOUlZwZnJqbHFFR3UzYlU9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTIzMTA4ODk3NDQ3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkU4MDBGREUwNUE3RDZERTBEQTA4RTNFNDQxRTY4RjZFIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzI5MDE5MDd9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6dHJ1ZX0sImRldmljZUlkIjoiQ21ORm5kOHlTYmFVZXdTNGh2Z1VGZyIsInBob25lSWQiOiJmZjEzOGQ1Mi0xZWQ1LTQwNzItOGU3ZC02ODU5ODFhNDVmMTYiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibHV2SHFYelVkMm1HUFdlL2oxTU5ZdDE5cXdNPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNYeCtnZzVLSjdpM1NQbWYxY1VnS0tXRTNybz0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiIyRjRTN1lOMiIsIm1lIjp7ImlkIjoiOTIzMTA4ODk3NDQ3OjdAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiUEFOSFdBUiJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTW1ZOUtrQ0VJTDRwN29HR0FRZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5Ijoidnd4NkdKQ2ZRSTlxQldOOXhKUCtZUCtsZXlsTzJLZHo5ek1UVm5ZZUtoWT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiZnlCZWpYd3FyRUZQNXpibHA3T0VCZ0V5MFhzNnRhSXdxOU9pVkRDY2gvWUQrQUJiZHNPaTgvWWVtYnk2REJzUlpWRFBUMXJCQmpjMUlRellndXJKQ1E9PSIsImRldmljZVNpZ25hdHVyZSI6ImdGSi9WeGhGZ1YwT3dHelA4UWJzbnFsTmpXaVprWWVUYnQ3QUdIYngxS3ltVDhIRTF0SlR4SjZZczE5dENZMWxQQWtiM2JiZHZTYnRzcjhSMXlnYkJ3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTIzMTA4ODk3NDQ3OjdAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYjhNZWhpUW4wQ1BhZ1ZqZmNTVC9tRC9wWHNwVHRpbmMvY3pFMVoySGlvVyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMjkwMTkwMywibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFIM3kifQ==",
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "©MrLegend",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "+923136420207",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
